# Generated by Django 2.2.4 on 2019-09-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puput', '0002_remove_entrypage_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrypage',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
