# Generated by Django 2.2.4 on 2019-09-26 09:02

import datetime
from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Article text'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 26, 11, 2, 26, 371772), verbose_name='Article Date'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Short intro'),
        ),
    ]
