# Generated by Django 2.2.4 on 2019-09-26 20:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190926_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 26, 20, 54, 15, 836971, tzinfo=utc), verbose_name='Article Date'),
        ),
    ]
