# Generated by Django 2.2.4 on 2020-11-03 20:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20201103_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 3, 20, 37, 42, 875402, tzinfo=utc), verbose_name='Article Date'),
        ),
    ]
