# Generated by Django 2.2.4 on 2019-09-03 11:10

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body2_en',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body2_ru',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
